// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Matheus-Lara/orare/internal/api/controller"
	"github.com/Matheus-Lara/orare/internal/api/service"
	"github.com/Matheus-Lara/orare/internal/db"
	"github.com/Matheus-Lara/orare/internal/repository"
	"github.com/Matheus-Lara/orare/internal/server"
)

// Injectors from wire.go:

func InitializeHttpServer() *server.HttpServer {
	healthService := service.NewHealthService()
	healthController := controller.NewHealthController(healthService)
	googleAuthService := service.NewGoogleAuthService()
	googleAuthController := controller.NewGoogleAuthController(googleAuthService)
	gormDB := db.GetConnection()
	userRepository := repository.NewUserRepository(gormDB)
	jwtService := service.NewJWTService()
	userAuthService := service.NewUserAuthService(userRepository, jwtService)
	userAuthController := controller.NewUserAuthController(userAuthService)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	adminController := controller.NewAdminController()
	httpServer := server.NewHttpServer(healthController, googleAuthController, userAuthController, userController, adminController)
	return httpServer
}
