services:
  postgres-db:
    container_name: postgres-db
    build:
      context: .docker/config/postgres
    platform: linux/x86_64
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER-root}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD-rootpassword}"
      POSTGRES_DB: "${POSTGRES_NAME-orare}"
    ports:
      - "${POSTGRES_PORT-5432}:5432"
    volumes:
      - ${POSTGRES_DATA_DIR-.docker/data/postgres}:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "${MAIL_PORT-1025}:1025"
      - "${MAILHOG_PORT-8025}:8025"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres-db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL-user@test.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD-password}
    ports:
      - "${PGADMIN_PORT-8081}:80"
    volumes:
      - ./.docker/data/pgadmin:/var/lib/pgadmin